server:
  port: 1111
 spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev      #开发环境
  application: 
      name: microservicesloud-config-yangyun-dev

---
spring: 
  profiles: test  # 测试环境
  application: 
    name: microservicesloud-config-yangyun-test
