spring: 
  profile: 
  active: 
  - dev
  
---
server: 
  port: 7001
  
spring: 
  profile: dev
  application: 
    name: microservicecloud-config-eureka-client


eureka: 
  instance: 
    hostname: eureka7001.com 
  client: 
    register-with-eureka: false   #当前eureka-server 自己不注册进服务列表中
    fetch-registry: false #不通过 eureka 获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/

---
server: 
  port: 7001  #注册中心占用 7001 端口, 冒号后面必须要有空格
  
spring: 
  profile: test
  application: 
    name: microservicecloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: eureka7001.com
  client: 
    registry-with-eureka: false
    fetch-registry: false
    service-url: 
  	  defaultZone: http://eureka7001.com:7001/eureka/
