spring:
  profile: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profile: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.107.172.70:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200 
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yangyun.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
    instance: 
      instance-id: dept-8001.com
      prefer-ip-address: true
info:
  app.name: yangyun-microservicecloud-springcloudconfig01
  company.name: www.yangyun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server: 
  port: 8001
spring: 
  profile: test
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.107.172.70:3306/cloudDB02              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200 
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yangyun.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
    instance: 
      instance-id: dept-8001.com
      prefer-ip-address: true
info:
  app.name: yangyun-microservicecloud-springcloudconfig02
  company.name: www.yangyun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
