spring: 
  profile: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
mybatis: 
  type-aliases-package: com.yangyun.springcloud.entities
  mapper-locations: - classpath:mybatis/mapper/**/*.xml
